title: "Poradnia psychologiczna dla dzieci i młodzieży"
description: "Profesjonalna pomoc psychologiczna dla dzieci i młodzieży."
baseurl: ""
url: "https://poradnia-synapsa.pl"
lang: pl
encoding: "utf-8"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
