title: "Poradnia Psychologiczna dla Dzieci"
description: "Profesjonalna pomoc psychologiczna dla dzieci i młodzieży."
baseurl: "/nowa-poradnia-synapsa.pl"
url: "https://str0k3.github.io"
lang: pl
encoding: "utf-8"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
